package com.mcode.mercadolibre.models.api

import com.google.gson.annotations.SerializedName

data class Body (

	@SerializedName("id") val id : String? = null,
	@SerializedName("site_id") val siteId : String? = null,
	@SerializedName("title") val title : String? = null,
	@SerializedName("subtitle") val subtitle : String? = null,
	@SerializedName("seller_id") val sellerId : Int? = null,
	@SerializedName("category_id") val categoryId : String? = null,
	@SerializedName("official_store_id") val officialStoreId : String? = null,
	@SerializedName("price") val price : Float? = null,
	@SerializedName("base_price") val basePrice : Float? = null,
	@SerializedName("original_price") val originalPrice : Float? = null,
	@SerializedName("currency_id") val currencyId : String? = null,
	@SerializedName("initial_quantity") val initialQuantity : Int? = null,
	@SerializedName("available_quantity") val availableQuantity : Int? = null,
	@SerializedName("sold_quantity") val soldQuantity : Int? = null,
	@SerializedName("sale_terms") val saleTerms : List<SaleTerms>? = emptyList(),
	@SerializedName("buying_mode") val buyingMode : String? = null,
	@SerializedName("listing_type_id") val listingTypeId : String? = null,
	@SerializedName("start_time") val startTime : String? = null,
	@SerializedName("stop_time") val stopTime : String? = null,
	@SerializedName("condition") val condition : String? = null,
	@SerializedName("permalink") val permalink : String? = null,
	@SerializedName("thumbnail_id") val thumbnailId : String? = null,
	@SerializedName("thumbnail") val thumbnail : String? = null,
	@SerializedName("secure_thumbnail") val secureThumbnail : String? = null,
	@SerializedName("pictures") val pictures : List<Pictures>? = emptyList(),
	@SerializedName("video_id") val videoId : String? = null,
	@SerializedName("descriptions") val descriptions : List<String>? = null,
	@SerializedName("accepts_mercadopago") val acceptsMercadopago : Boolean? = null,
	@SerializedName("shipping") val shipping : Shipping? = null,
	@SerializedName("international_delivery_mode") val internationalDeliveryMode : String? = null,
	@SerializedName("seller_address") val sellerAddress : SellerAddress? = null,
	@SerializedName("coverage_areas") val coverageAreas : List<String>? = null,
	@SerializedName("attributes") val attributes : List<Attributes>? = emptyList(),
	@SerializedName("warnings") val warnings : List<String>? = null,
	@SerializedName("listing_source") val listingSource : String? = null,
	@SerializedName("status") val status : String? = null,
	@SerializedName("sub_status") val subStatus : List<String>? = null,
	@SerializedName("tags") val tags : List<String>? = null,
	@SerializedName("warranty") val warranty : String? = null,
	@SerializedName("catalog_product_id") val catalogProductId : String? = null,
	@SerializedName("domain_id") val domainId : String? = null,
	@SerializedName("parent_item_id") val parentItemId : String? = null,
	@SerializedName("differential_pricing") val differentialPricing : String? = null,
	@SerializedName("deal_ids") val dealIds : List<String>? = null,
	@SerializedName("automatic_relist") val automaticRelist : Boolean? = null,
	@SerializedName("date_created") val dateCreated : String? = null,
	@SerializedName("last_updated") val lastUpdated : String? = null,
	@SerializedName("health") val health : String? = null,
	@SerializedName("catalog_listing") val catalogListing : Boolean? = null,
	@SerializedName("channels") val channels : List<String>? = emptyList()
)